security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

    main:
      lazy: true
      provider: app_user_provider

      # Authentification par formulaire
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: app_welcome
        always_use_default_target_path: true

      logout:
        path: app_logout
        target: /

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/photos, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api/themes, roles: PUBLIC_ACCESS, methods: [GET] }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/welcome, roles: ROLE_USER }

